/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProposeRouteImport } from './routes/propose'
import { Route as ForeverRouteImport } from './routes/forever'
import { Route as IndexRouteImport } from './routes/index'

const ProposeRoute = ProposeRouteImport.update({
  id: '/propose',
  path: '/propose',
  getParentRoute: () => rootRouteImport,
} as any)
const ForeverRoute = ForeverRouteImport.update({
  id: '/forever',
  path: '/forever',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forever': typeof ForeverRoute
  '/propose': typeof ProposeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forever': typeof ForeverRoute
  '/propose': typeof ProposeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forever': typeof ForeverRoute
  '/propose': typeof ProposeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/forever' | '/propose'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/forever' | '/propose'
  id: '__root__' | '/' | '/forever' | '/propose'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForeverRoute: typeof ForeverRoute
  ProposeRoute: typeof ProposeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/propose': {
      id: '/propose'
      path: '/propose'
      fullPath: '/propose'
      preLoaderRoute: typeof ProposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forever': {
      id: '/forever'
      path: '/forever'
      fullPath: '/forever'
      preLoaderRoute: typeof ForeverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForeverRoute: ForeverRoute,
  ProposeRoute: ProposeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
